openapi: 3.0.0
info:
  title: Customer Feedback API
  version: 1.0.0
  description: API for collecting and managing customer feedback.
servers:
  - url: https://api1-project-files.onrender.com
paths:
  /feedback:
    post:
      summary: Submit customer feedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerName:
                  type: string
                email:
                  type: string
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                comments:
                  type: string
              required:
                - customerName
                - email
      responses:
        '201':
          description: Feedback created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
    get:
      summary: Retrieve all feedback
      responses:
        '200':
          description: A list of feedback entries.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feedback'
  /feedback/{feedbackId}:
    get:
      summary: Retrieve a single feedback entry
      parameters:
        - in: path
          name: feedbackId
          schema:
            type: integer
          required: true
          description: Numeric ID of the feedback entry.
      responses:
        '200':
          description: Details of the feedback entry.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
        '404':
          description: Feedback not found.
    put:
      summary: Update a feedback entry
      parameters:
        - in: path
          name: feedbackId
          schema:
            type: integer
          required: true
          description: Numeric ID of the feedback entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feedback'
      responses:
        '200':
          description: Feedback updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
        '404':
          description: Feedback not found.
    delete:
      summary: Delete a feedback entry
      parameters:
        - in: path
          name: feedbackId
          schema:
            type: integer
          required: true
          description: Numeric ID of the feedback entry.
      responses:
        '200':
          description: Feedback deleted successfully.
        '404':
          description: Feedback not found.
components:
  schemas:
    Feedback:
      type: object
      properties:
        id:
          type: integer
        customerName:
          type: string
        email:
          type: string
        rating:
          type: integer
        comments:
          type: string
